<?php

namespace Database\Seeders;

use App\Models\AnimalEdit;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AnimalEditSeeder extends Seeder
{
    public function run(): void
    {
        $edits = [
            [
                'status' => 'lost',
                'title' => 'Zaginął rottweiler – Gdynia',
                'description' => 'Rex uciekł przez dziurę w ogrodzeniu. Jest łagodny mimo groźnego wyglądu.',
                'animal_name' => 'Rex',
                'ident_marks' => 'Czarno-brązowy, duża budowa ciała',
                'chip_present' => true,
                'chip_number' => '616093900555666',
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-26',
                'voivodeship_id' => 11,
                'city_id' => 1,
                'location_text' => 'Chylonia, Gdynia',
                'latitude' => 54.5189,
                'longitude' => 18.5305,
                'contact_name' => 'Marcin Dąbrowski',
                'contact_email' => 'm.dabrowski@example.com',
                'contact_phone' => '610200300',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono perskiego kota – Rzeszów',
                'description' => 'Zaniedbany kot perski znaleziony przy parku. Wymaga opieki weterynaryjnej.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Kremowe, długie futro, spłaszczony pysk',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-27',
                'voivodeship_id' => 9,
                'city_id' => 2,
                'location_text' => 'Park Miejski, Rzeszów',
                'latitude' => 50.0412,
                'longitude' => 22.0042,
                'contact_name' => 'Dorota Kubiak',
                'contact_email' => 'd.kubiak@example.com',
                'contact_phone' => '611300400',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął jamnik – Toruń',
                'description' => 'Kiszka uciekł ze smyczy podczas spaceru. Reaguje na swoje imię.',
                'animal_name' => 'Kiszka',
                'ident_marks' => 'Brązowy, długie uszy, krótkie nóżki',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-25',
                'voivodeship_id' => 2,
                'city_id' => 3,
                'location_text' => 'Starówka, Toruń',
                'latitude' => 53.0138,
                'longitude' => 18.5981,
                'contact_name' => 'Łukasz Jankowski',
                'contact_email' => 'l.jankowski@example.com',
                'contact_phone' => '612400500',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginęła biało-ruda kotka – Białystok',
                'description' => 'Ruda wyszła rano i nie wróciła. Jest wysterylizowana i bardzo oswojona.',
                'animal_name' => 'Ruda',
                'ident_marks' => 'Biało-rude łaty, zielone oczy',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-27',
                'voivodeship_id' => 10,
                'city_id' => 4,
                'location_text' => 'Osiedle Słoneczny Stok, Białystok',
                'latitude' => 53.1325,
                'longitude' => 23.1688,
                'contact_name' => 'Agnieszka Pawlak',
                'contact_email' => 'a.pawlak@example.com',
                'contact_phone' => '613500600',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono owczarka niemieckiego – Kielce',
                'description' => 'Dorosły owczarek znaleziony przy autostradzie A1. Wygląda na zadbany.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Czarno-brązowy, duży pies, posłuszny',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 2,
                'date_event' => '2026-06-26',
                'voivodeship_id' => 13,
                'city_id' => 5,
                'location_text' => 'Okolice autostrady A1, Kielce',
                'latitude' => 50.8661,
                'longitude' => 20.6286,
                'contact_name' => 'Stanisław Wróbel',
                'contact_email' => 's.wrobel@example.com',
                'contact_phone' => '614600700',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął szpic miniaturowy – Opole',
                'description' => 'Puszek to mały rudy szpic. Ucieka do obcych ludzi, więc może być gdzieś przetrzymywany.',
                'animal_name' => 'Puszek',
                'ident_marks' => 'Rude puszyste futerko, mała budowa',
                'chip_present' => true,
                'chip_number' => '616093900777888',
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-24',
                'voivodeship_id' => 8,
                'city_id' => 1,
                'location_text' => 'Centrum, Opole',
                'latitude' => 50.6751,
                'longitude' => 17.9213,
                'contact_name' => 'Monika Grabowska',
                'contact_email' => 'm.grabowska@example.com',
                'contact_phone' => '615700800',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono czarno-białego kota – Olsztyn',
                'description' => 'Kot znaleziony w garażu podziemnym. Głodny i przestraszony, ale bez obrażeń.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Czarno-biały, krótkie futro',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-27',
                'voivodeship_id' => 14,
                'city_id' => 2,
                'location_text' => 'Śródmieście, Olsztyn',
                'latitude' => 53.7784,
                'longitude' => 20.4801,
                'contact_name' => 'Krzysztof Michalski',
                'contact_email' => 'k.michalski@example.com',
                'contact_phone' => '616800900',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął husky – Zielona Góra',
                'description' => 'Śnieżek uciekł podczas zabawy w lesie. Ma zielony chip i zwykle wraca na gwizdek.',
                'animal_name' => 'Śnieżek',
                'ident_marks' => 'Szaro-biały, jedno brązowe i jedno niebieskie oko',
                'chip_present' => true,
                'chip_number' => '616093900999000',
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-28',
                'voivodeship_id' => 4,
                'city_id' => 3,
                'location_text' => 'Las Odrzański, Zielona Góra',
                'latitude' => 51.9356,
                'longitude' => 15.5062,
                'contact_name' => 'Barbara Adamczyk',
                'contact_email' => 'b.adamczyk@example.com',
                'contact_phone' => '617900100',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginęła kotka maine coon – Gorzów Wlkp.',
                'description' => 'Duża ruda kotka o imieniu Figa. Wyszła przez balkon na 3 piętrze.',
                'animal_name' => 'Figa',
                'ident_marks' => 'Duże rude futro, kępki na uszach, puszysty ogon',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-28',
                'voivodeship_id' => 4,
                'city_id' => 4,
                'location_text' => 'Osiedle Słowiańskie, Gorzów Wlkp.',
                'latitude' => 52.7368,
                'longitude' => 15.2288,
                'contact_name' => 'Paweł Ostrowski',
                'contact_email' => 'p.ostrowski@example.com',
                'contact_phone' => '618100200',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono labradora – Radom',
                'description' => 'Żółty labrador znaleziony na osiedlu. Jest zadbany i ma chip, ale skaner nie odczytał numeru.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Złote umaszczenie, bardzo towarzyski',
                'chip_present' => true,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-27',
                'voivodeship_id' => 7,
                'city_id' => 5,
                'location_text' => 'Osiedle XV-lecia, Radom',
                'latitude' => 51.4027,
                'longitude' => 21.1471,
                'contact_name' => 'Natalia Kwiatkowska',
                'contact_email' => 'n.kwiatkowska@example.com',
                'contact_phone' => '619200300',
            ],
        ];

        foreach ($edits as $data) {
            AnimalEdit::create(array_merge($data, [
                'mod_status' => 'pending',
                'edit_token' => Str::uuid(),
            ]));
        }
    }
}
