<?php

namespace Database\Seeders;

use App\Models\Animal;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class AnimalSeeder extends Seeder
{
    public function run(): void
    {
        $animals = [
            [
                'status' => 'lost',
                'title' => 'Zaginął brązowy labrador – Warszawa',
                'description' => 'Max zaginął podczas spaceru w Parku Skaryszewskim. Jest przyjazny i łatwo nawiązuje kontakt z ludźmi.',
                'animal_name' => 'Max',
                'ident_marks' => 'Blizna na lewej łapie, obroża niebieska',
                'chip_present' => true,
                'chip_number' => '616093900123456',
                'species_id' => 1,
                'breed_id' => 2,
                'date_event' => '2026-06-15',
                'voivodeship_id' => 7,
                'city_id' => 1,
                'location_text' => 'Park Skaryszewski, Warszawa',
                'latitude' => 52.2297,
                'longitude' => 21.0122,
                'contact_name' => 'Anna Kowalska',
                'contact_email' => 'anna.kowalska@example.com',
                'contact_phone' => '600100200',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono rudego kota – Kraków',
                'description' => 'Ruda kotka znaleziona pod blokiem przy ul. Długiej. Jest wychudzona, ale spokojna.',
                'animal_name' => 'Nieznana',
                'ident_marks' => 'Rude umaszczenie, biała łatka na brzuchu',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-20',
                'voivodeship_id' => 6,
                'city_id' => 2,
                'location_text' => 'ul. Długa 12, Kraków',
                'latitude' => 50.0614,
                'longitude' => 19.9366,
                'contact_name' => 'Piotr Nowak',
                'contact_email' => 'piotr.nowak@example.com',
                'contact_phone' => '601200300',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął owczarek australijski – Wrocław',
                'description' => 'Burek uciekł przez otwartą furtkę. Ma charakterystyczne niebieskie oczy.',
                'animal_name' => 'Burek',
                'ident_marks' => 'Merle umaszczenie, jedno niebieskie oko',
                'chip_present' => true,
                'chip_number' => '616093900654321',
                'species_id' => 1,
                'breed_id' => 7,
                'date_event' => '2026-06-18',
                'voivodeship_id' => 1,
                'city_id' => 3,
                'location_text' => 'Osiedle Różanka, Wrocław',
                'latitude' => 51.1079,
                'longitude' => 17.0385,
                'contact_name' => 'Katarzyna Wiśniewska',
                'contact_email' => 'k.wisniewska@example.com',
                'contact_phone' => '602300400',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginęła czarna kotka – Gdańsk',
                'description' => 'Luna uciekła przez otwarte okno. Jest kastrowana i bardzo płochliwa.',
                'animal_name' => 'Luna',
                'ident_marks' => 'Cała czarna, biały koniuszek ogona',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-22',
                'voivodeship_id' => 11,
                'city_id' => 4,
                'location_text' => 'Wrzeszcz, Gdańsk',
                'latitude' => 54.3753,
                'longitude' => 18.6201,
                'contact_name' => 'Tomasz Zając',
                'contact_email' => 't.zajac@example.com',
                'contact_phone' => '603400500',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono golden retrievera – Poznań',
                'description' => 'Przyjazny pies znaleziony przy dworcu. Ma obrożę, ale bez adresatki.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Złote umaszczenie, obroża czerwona bez adresatki',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-21',
                'voivodeship_id' => 15,
                'city_id' => 5,
                'location_text' => 'Dworzec Główny, Poznań',
                'latitude' => 52.4064,
                'longitude' => 16.9252,
                'contact_name' => 'Magdalena Krawczyk',
                'contact_email' => 'm.krawczyk@example.com',
                'contact_phone' => '604500600',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął beagle – Łódź',
                'description' => 'Rocky uciekł podczas burzy i nie wrócił do domu. Szczeka na inne psy.',
                'animal_name' => 'Rocky',
                'ident_marks' => 'Trójkolorowy, czerwona obroża z dzwoneczkiem',
                'chip_present' => true,
                'chip_number' => '616093900111222',
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-19',
                'voivodeship_id' => 5,
                'city_id' => 1,
                'location_text' => 'Retkinia, Łódź',
                'latitude' => 51.7592,
                'longitude' => 19.3974,
                'contact_name' => 'Jakub Lewandowski',
                'contact_email' => 'j.lewandowski@example.com',
                'contact_phone' => '605600700',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono szarego kota – Lublin',
                'description' => 'Szary kot siedział przy śmietniku, jest bardzo głodny. Wygląda na zagubionego.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Szare umaszczenie, zielone oczy',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-23',
                'voivodeship_id' => 3,
                'city_id' => 2,
                'location_text' => 'ul. Narutowicza, Lublin',
                'latitude' => 51.2465,
                'longitude' => 22.5684,
                'contact_name' => 'Alicja Wójcik',
                'contact_email' => 'a.wojcik@example.com',
                'contact_phone' => '606700800',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginął biały maltańczyk – Katowice',
                'description' => 'Puszek zaginął w okolicy galerii handlowej. Jest mały i bardzo towarzyski.',
                'animal_name' => 'Puszek',
                'ident_marks' => 'Cały biały, różowa kokardka na szyi',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 1,
                'date_event' => '2026-06-17',
                'voivodeship_id' => 12,
                'city_id' => 3,
                'location_text' => 'Silesia City Center, Katowice',
                'latitude' => 50.2649,
                'longitude' => 19.0238,
                'contact_name' => 'Bożena Mazur',
                'contact_email' => 'b.mazur@example.com',
                'contact_phone' => '607800900',
            ],
            [
                'status' => 'lost',
                'title' => 'Zaginęła kotka syjamska – Szczecin',
                'description' => 'Kleo uciekła przez balkon. Jest bardzo wokalna i lubi ludzi.',
                'animal_name' => 'Kleo',
                'ident_marks' => 'Syjamskie umaszczenie, niebieskie oczy',
                'chip_present' => true,
                'chip_number' => '616093900333444',
                'species_id' => 2,
                'breed_id' => 1,
                'date_event' => '2026-06-24',
                'voivodeship_id' => 16,
                'city_id' => 4,
                'location_text' => 'Śródmieście, Szczecin',
                'latitude' => 53.4289,
                'longitude' => 14.5530,
                'contact_name' => 'Rafał Kowalczyk',
                'contact_email' => 'r.kowalczyk@example.com',
                'contact_phone' => '608900100',
            ],
            [
                'status' => 'found',
                'title' => 'Znaleziono border collie – Bydgoszcz',
                'description' => 'Pies znaleziony na polach przy obwodnicy. Jest wyczerpany, ale zdrowy.',
                'animal_name' => 'Nieznany',
                'ident_marks' => 'Czarno-biały, bardzo inteligentny wzrok',
                'chip_present' => false,
                'chip_number' => null,
                'species_id' => 1,
                'breed_id' => 8,
                'date_event' => '2026-06-25',
                'voivodeship_id' => 2,
                'city_id' => 5,
                'location_text' => 'Fordon, Bydgoszcz',
                'latitude' => 53.1235,
                'longitude' => 18.0076,
                'contact_name' => 'Ewa Szymańska',
                'contact_email' => 'e.szymanska@example.com',
                'contact_phone' => '609100200',
            ],
        ];

        foreach ($animals as $data) {
            Animal::create(array_merge($data, [
                'mod_status' => 'approved',
                'edit_token' => Str::uuid(),
            ]));
        }
    }
}
